web:
  kind: "helm_release"
  match:
    chart_name: "web"
  policies:
  - path: "./policies/web/web_version.rego"
    name: "web.version"
nginx:
  kind: "helm_release"
  match:
    name: nginx-ingress
    namespace: ingress-nginx
  policies:
  - path: "./policies/nginx/nginx_version.rego"
    name: "nginx.version"
  - path: "./policies/nginx/nginx_topology_spread_constraints.rego"
    name: "nginx.topology_spread_constraints"
  - path: "./policies/nginx/memory_limits.rego"
    name: "nginx.memory_limits"
  - path: "./policies/nginx/wait_shutdown.rego"
    name: "nginx.wait_shutdown"
prometheus:
  kind: "helm_release"
  match:
    name: prometheus
    namespace: monitoring
  policies:
  - path: "./policies/prometheus/server_memory_limits.rego"
    name: "prometheus.server_memory_limits"
  - path: "./policies/prometheus/alertmanager_memory_limits.rego"
    name: "prometheus.alertmanager_memory_limits"
  - path: "./policies/prometheus/kubestatemetrics_memory_limits.rego"
    name: "prometheus.kubestatemetrics_memory_limits"
  - path: "./policies/prometheus/pushgateway_memory_limits.rego"
    name: "prometheus.pushgateway_memory_limits"
  - path: "./policies/prometheus/nodeexporter_memory_limits.rego"
    name: "prometheus.nodeexporter_memory_limits"
nginx_pod:
  kind: "pod"
  match:
    namespace: ingress-nginx
    labels:
      app.kubernetes.io/component: "controller"
      app.kubernetes.io/instance: "nginx-ingress"
      app.kubernetes.io/name: "ingress-nginx"
  policies:
  - path: "./policies/pod/running.rego"
    name: "pod.running"